source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
use_frameworks!

target 'Restaurants' do

pod "Alamofire" #API requests
pod "AlamofireImage" #Image queueing for loading

pod "ReachabilitySwift" #Check for Network status

pod "KeychainSwift" #This is a collection of helper functions for saving text and data in the Keychain

    target 'RestaurantsTests' do
        inherit! :search_paths
        pod "Alamofire" #API requests
    end

end
